### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

### Importing Data

In [2]:
data_path = r'C:\Users\gerar\CareerFoundry Python\Instacart Basket Analysis\02 Data'

In [4]:
df_orders_products_merge = pd.read_pickle(os.path.join(data_path, 'Prepared Data', 'orders_products_merge_busy.pkl'))

In [5]:
#check shape
df_orders_products_merge.shape

(32404859, 18)

### Lesson

In [6]:
# use  groupby().agg() for a single aggregation (BEST PRACTICE)
df_orders_products_merge.groupby('department_id').agg({'customer_order_count': ['mean']})

              customer_order_count
                              mean
department_id
1                        15.457838
2                        17.277920
3                        17.170395
4                        17.811403
5                        15.215751
6                        16.439806
7                        17.225802
8                        15.340650
9                        15.895474
10                       20.197148
11                       16.170638
12                       15.887671
13                       16.583536
14                       16.773669
15                       16.165037
16                       17.665606
17                       15.694469
18                       19.310397
19                       17.177343
20                       16.473447
21                       22.902379

In [8]:
# calculating multiple aggregations (best practice)
df_orders_products_merge.groupby('department_id').agg({'customer_order_count' : ['mean', 'min', 'max']})

              customer_order_count
                              mean min max
department_id
1                        15.457838   1  99
2                        17.277920   1  99
3                        17.170395   1  99
4                        17.811403   1  99
5                        15.215751   1  99
6                        16.439806   1  99
7                        17.225802   1  99
8                        15.340650   1  99
9                        15.895474   1  99
10                       20.197148   1  99
11                       16.170638   1  99
12                       15.887671   1  99
13                       16.583536   1  99
14                       16.773669   1  99
15                       16.165037   1  99
16                       17.665606   1  99
17                       15.694469   1  99
18                       19.310397   1  99
19                       17.177343   1  99
20                       16.473447   1  99
21                       22.902379   1  99

In [13]:
# use head() to have a quick-view of column names and data contents
df_orders_products_merge.head(1)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders

In [15]:
# create a flag column using an aggregated criteria through transform()
# future warning: transform(pd.max) will turn into transform('max') in the future. Recommended to use transform('max') instead.

df_orders_products_merge['max_order'] = df_orders_products_merge.groupby(['user_id'])['customer_order_count'].transform('max')

In [18]:
# check functionality
df_orders_products_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid_range_price,Least busy,Least busy days,Average orders,3

In [19]:
# declares empty list that will fill the 'loyalty_flag' column
flag_values_list = []

# for loop that fills the empty list 
for value in df_orders_products_merge['max_order']:  
    if value > 40:
        flag_values_list.append('Loyal customer')
    elif value <= 40 and value > 10:
        flag_values_list.append('Regular customer')
    else:
        flag_values_list.append('New customer')

In [20]:
# create a column in the dataframe. Values come from "flag_values_list"
df_orders_products_merge['loyalty_flag'] = flag_values_list

In [27]:
# check functionality
df_orders_products_merge.tail(50)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order,loyalty_flag
32404809,49688,Fresh Foaming Cleanser,73,11,13.5,2732438,111542,10,0,21,5.0,3,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,29,Regular customer
32404810,49688,Fresh Foaming Cleanser,73,11,13.5,2996443,114963,12,1,14,16.0,19,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,45,Loyal customer
32404811,49688,Fresh Foaming Cleanser,73,11,13.5,891179,118871,7,1,9,2.0,4,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,35,Regular customer
32404812,49688,Fresh Foaming Cleanser,73,11,13.5,3290206,121646,3,0,9,14.0,10,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,11,Regular customer
32404813,49688,Fresh Foaming Cleanser,73,11,13.5,2951582,124944,6,0,15,30.0,12,0,both,Mid_range_price,Busiest day,Busiest days,Most orders,6,New customer
32404814,49688,Fresh Foaming Cleanser,73,11,13.5,328141,128148,3,0,11,7.0,10,0,both,Mid_range_price,Busiest day,Busiest days,Most orders,33,Regular customer
32404815,49688,Fresh Foaming Cleanser,73,11,13.5,3041952,128148,28,0,11,5.0,1,1,both,Mid_range_price,Busiest day,Busiest days,Most orders,33,Regular customer
32404816,49688,Fresh Foaming Cleanser,73,11,13.5,1897157,128930,7,0,16,30.0,14,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,11,Regular customer
32404817,49688,Fresh Foaming Cleanser,73,11,13.5,2476113,128930,9,5,13,30.0,7,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,11,Regular customer
32404818,49688,Fresh Foaming Cleanser,73,11,13.5,1631554,129901,2,5,11,30.0,23,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,4,New customer
32404819,49688,Fresh Foaming Cleanser,73,11,13.5,641382,142639,26,5,14,30.0,6,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,27,Regular customer
32404820,49688,Fresh Foaming Cleanser,73,11,13.5,253490,144914,16,1,8,9.0,20,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,28,Regular customer
32404821,49688,Fresh Foaming Cleanser,73,11,13.5,965803,145111,1,3,17,NaN,20,0,both,Mid_range_price,Regularly busy,Least busy days,Average orders,16,Regular customer
32404822,49688,Fresh Foaming Cleanser,73,11,13.5,393166,145526,23,1,11,11.0,34,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,23,Regular customer
32404823,49688,Fresh Foaming Cleanser,73,11,13.5,3058519,145732,4,0,8,19.0,8,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,8,New customer
32404824,49688,Fresh Foaming Cleanser,73,11,13.5,3122003,146323,3,1,16,24.0,20,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,9,New customer
32404825,49688,Fresh Foaming Cleanser,73,11,13.5,2779979,151977,1,0,16,NaN,8,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,8,New customer
32404826,49688,Fresh Foaming Cleanser,73,11,13.5,2363598,153612,1,6,11,NaN,1,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,5,New customer
32404827,49688,Fresh Foaming Cleanser,73,11,13.5,967902,157883,3,0,17,30.0,6,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,3,New customer
32404828,49688,Fresh Foaming Cleanser,73,11,13.5,2932449,159099,2,2,14,15.0,3,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,9,New customer
32404829,49688,Fresh Foaming Cleanser,73,11,13.5,2744037,159487,1,2,18,NaN,2,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,14,Regular customer
32404830,49688,Fresh Foaming Cleanser,73,11,13.5,13797,159487,8,0,12,14.0,2,1,both,Mid_range_price,Busiest day,Busiest days,Most orders,14,Regular customer
32404831,49688,Fresh Foaming Cleanser,73,11,13.5,258779,159487,11,2,20,17.0,2,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,14,Regular customer
32404832,49688,Fresh Foaming Cleanser,73,11,13.5,311401,159487,13,4,18,30.0,1,1,both,Mid_range_price,Least busy,Least busy days,Average orders,14,Regular customer
32404833,49688,Fresh Foaming Cleanser,73,11,13.5,425916,159638,2,6,15,30.0,8,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,7,New customer
32404834,49688,Fresh Foaming Cleanser,73,11,13.5,2530161,163632,1,3,12,NaN,1,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,8,New customer
32404835,49688,Fresh Foaming Cleanser,73,11,13.5,1288677,163632,3,1,8,30.0,1,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,8,New customer
32404836,49688,Fresh Foaming Cleanser,73,11,13.5,3008450,164453,6,0,12,5.0,8,0,both,Mid_range_price,Busiest day,Busiest days,Most orders,24,Regular customer
32404837,49688,Fresh Foaming Cleanser,73,11,13.5,151501,166038,2,2,16,10.0,4,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,15,Regular customer
32404838,49688,Fresh Foaming Cleanser,73,11,13.5,2439935,166038,7,4,21,30.0,9,1,both,Mid_range_price,Least busy,Least busy days,Average orders,15,Regular customer
32404839,49688,Fresh Foaming Cleanser,73,11,13.5,1400940,166213,1,1,21,NaN,4,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,3,New customer
32404840,49688,Fresh Foaming Cleanser,73,11,13.5,1219750,171743,5,0,8,30.0,24,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,10,New customer
32404841,49688,Fresh Foaming Cleanser,73,11,13.5,307087,172262,4,6,11,30.0,15,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,4,New customer
32404842,49688,Fresh Foaming Cleanser,73,11,13.5,2454083,176942,2,6,20,3.0,8,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,4,New customer
32404843,49688,Fresh Foaming Cleanser,73,11,13.5,2710528,178693,26,5,10,3.0,18,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,60,Loyal customer
32404844,49688,Fresh Foaming Cleanser,73,11,13.5,1173882,178752,7,0,23,21.0,28,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,16,Regular customer
32404845,49688,Fresh Foaming Cleanser,73,11,13.5,1525694,178752,15,5,10,30.0,3,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,16,Regular customer
32404846,49688,Fresh Foaming Cleanser,73,11,13.5,2439069,182948,4,6,16,13.0,1,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,8,New customer
32404847,49688,Fresh Foaming Cleanser,73,11,13.5,2392655,182948,8,2,11,16.0,28,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,8,New customer
32404848,49688,Fresh Foaming Cleanser,73,11,13.5,848810,183548,15,2,16,30.0,22,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,15,Regular customer
32404849,49688,Fresh Foaming Cleanser,73,11,13.5,2251059,184081,1,6,9,NaN,4,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,11,Regular customer
32404850,49688,Fresh Foaming Cleanser,73,11,13.5,846716,187523,14,3,11,9.0,8,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,17,Regular customer
32404851,49688,Fresh Foaming Cleanser,73,11,13.5,362546,188073,5,2,4,30.0,4,0,both,Mid_range_price,Regularly busy,Regularly busy,Fewest orders,31,Regular customer
32404852,49688,Fresh Foaming Cleanser,73,11,13.5,3166828,188073,7,1,15,30.0,5,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,31,Regular customer
32404853,49688,Fresh Foaming Cleanser,73,11,13.5,3106363,197371,10,4,14,30.0,17,0,both,Mid_range_price,Least busy,Least busy days,Most orders,10,New customer
32404854,49688,Fresh Foaming Cleanser,73,11,13.5,1788356,200215,2,0,9,5.0,27,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,6,New customer
32404855,49688,Fresh Foaming Cleanser,73,11,13.5,3401313,200377,1,4,11,NaN,5,0,both,Mid_range_price,Least busy,Least busy days,Most orders,4,New customer
32404856,49688,Fresh Foaming Cleanser,73,11,13.5,809510,200873,5,3,8,15.0,12,0,both,Mid_range_price,Regularly busy,Least busy days,Average orders,20,Regular customer
32404857,49688,Fresh Foaming Cleanser,73,11,13.5,2359893,200873,9,3,15,5.0,11,1,both,Mid_range_price,Regularly busy,Least busy days,Most orders,20,Regular customer
32404858,49688,Fresh Foaming Cleanser,73,11,13.5,2385091,205926,11,1,15,6.0,35,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,11,Regular customer

In [28]:
# count values of 'loyalty_flag' column
df_orders_products_merge['loyalty_flag'].value_counts()

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [35]:
# quick-view
df_orders_products_merge[['user_id', 'max_order', 'loyalty_flag']].head(50)

    user_id  max_order      loyalty_flag
0       138         32  Regular customer
1       138         32  Regular customer
2       709          5      New customer
3       764          3      New customer
4       764          3      New customer
5       777         26  Regular customer
6       825          9      New customer
7       910         12  Regular customer
8      1052         20  Regular customer
9      1052         20  Regular customer
10     1379         10      New customer
11     1480         43    Loyal customer
12     1480         43    Loyal customer
13     1480         43    Loyal customer
14     1494         13  Regular customer
15     1494         13  Regular customer
16     1494         13  Regular customer
17     1540         28  Regular customer
18     1540         28  Regular customer
19     1540         28  Regular customer
20     1540         28  Regular customer
21     1540         28  Regular customer
22     1540         28  Regular customer
23     1540         28  Regular customer
24     1540         28  Regular customer
25     1540         28  Regular customer
26     1540         28  Regular customer
27     1540         28  Regular customer
28     1540         28  Regular customer
29     1540         28  Regular customer
30     1540         28  Regular customer
31     1540         28  Regular customer
32     1540         28  Regular customer
33     1540         28  Regular customer
34     1598          4      New customer
35     1598          4      New customer
36     1598          4      New customer
37     1647         10      New customer
38     1647         10      New customer
39     1647         10      New customer
40     1647         10      New customer
41     1647         10      New customer
42     2833         10      New customer
43     2850         23  Regular customer
44     2857         25  Regular customer
45     3010         13  Regular customer
46     3029          5      New customer
47     3395          6      New customer
48     3904          3      New customer
49     4006         42    Loyal customer

# Task

### 1. Mean of "order_number" grouped by "department_id"

In [36]:
# use  groupby().agg() for a single aggregation (BEST PRACTICE)
df_orders_products_merge.groupby('department_id').agg({'customer_order_count': ['mean']})

              customer_order_count
                              mean
department_id
1                        15.457838
2                        17.277920
3                        17.170395
4                        17.811403
5                        15.215751
6                        16.439806
7                        17.225802
8                        15.340650
9                        15.895474
10                       20.197148
11                       16.170638
12                       15.887671
13                       16.583536
14                       16.773669
15                       16.165037
16                       17.665606
17                       15.694469
18                       19.310397
19                       17.177343
20                       16.473447
21                       22.902379

### 3. Result analysis

I have the result in another notebook but basically the subset means have different values than the full dataframe means. However, the range of difference comparing each department is approximately the following: ± (0.1 to 2.5)

### 4. Creating a loyalty flag with transform() and loc()

In [ ]:
# transform() was already used in the dataframe I have a second notebook which is the lesson notebook.
# I used the tranform() on the subset slice there.

In [39]:
# use .loc to flag loyal customers having more than 40 max_order
df_orders_products_merge.loc[df_orders_products_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [40]:
# use ".loc" to flag regular customers. They have between 10 and 40 orders
df_orders_products_merge.loc[(df_orders_products_merge['max_order'] <= 40) & (df_orders_products_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [41]:
# use ".loc" to flag new customers. They have less than 10 orders
df_orders_products_merge.loc[df_orders_products_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [43]:
# check functionality
df_orders_products_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid_range_price,Least busy,Least busy days,Average orders,3,New customer

### 5. Price comparison among groups of customers

In [44]:
# (min,max,mean,std) aggregations for the 'prices' column. Grouped by loyalty flag.
df_orders_products_merge.groupby('loyalty_flag').agg({'prices': ['min','max','mean', 'std']})

                 prices
                    min      max       mean         std
loyalty_flag
Loyal customer      1.0  99999.0  10.386336  328.017787
New customer        1.0  99999.0  13.294670  597.560299
Regular customer    1.0  99999.0  12.495717  539.720919

In [45]:
# comparing with min and max price to check for mistakes. 
df_orders_products_merge.describe()

,product_id,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,max_order
count,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.032876e+07,3.240486e+07,3.240486e+07,3.240486e+07
mean,2.559866e+04,7.119612e+01,9.919792e+00,1.198023e+01,1.710745e+06,1.029372e+05,1.714230e+01,2.738867e+00,1.342515e+01,1.110408e+01,8.352547e+00,5.895873e-01,3.305217e+01
std,1.408400e+04,3.821139e+01,6.281485e+00,4.956554e+02,9.872988e+05,5.946610e+04,1.753532e+01,2.090077e+00,4.246380e+00,8.779064e+00,7.127071e+00,4.919087e-01,2.515525e+01
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00
25%,1.354400e+04,3.100000e+01,4.000000e+00,4.200000e+00,8.559470e+05,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,3.000000e+00,0.000000e+00,1.300000e+01
50%,2.530200e+04,8.300000e+01,9.000000e+00,7.400000e+00,1.711049e+06,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,6.000000e+00,1.000000e+00,2.600000e+01
75%,3.794700e+04,1.070000e+02,1.600000e+01,1.130000e+01,2.565499e+06,1.543890e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,1.100000e+01,1.000000e+00,4.700000e+01
max,4.968800e+04,1.340000e+02,2.100000e+01,9.999900e+04,3.421083e+06,2.062090e+05,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01,1.450000e+02,1.000000e+00,9.900000e+01

### 6. Creating a spending flag for customers

In [46]:
# create a column using aggregation through transform(). Mean aggregation of 'prices'. Groupby 'user_id'.

df_orders_products_merge['mean_price'] = df_orders_products_merge.groupby(['user_id'])['prices'].transform('mean')

In [47]:
# check functionality
df_orders_products_merge.head(40)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,...,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order,loyalty_flag,mean_price
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,20,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,10,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,11,1,both,Mid_range_price,Least busy,Least busy days,Average orders,3,New customer,4.972414
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,7,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,26,Regular customer,6.935398
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,2,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,9,New customer,5.957576
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,1,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,12,Regular customer,6.680000
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,1,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,20,Regular customer,7.162500
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,2,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,20,Regular customer,7.162500
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,...,1,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,10,New customer,5.813636
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,...,1,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,43,Loyal customer,5.081633
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,...,3,1,both,Mid_range_price,Least busy,Least busy days,Most orders,43,Loyal customer,5.081633
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,...,4,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,43,Loyal customer,5.081633
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,...,8,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,13,Regular customer,6.803797
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,...,18,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,...,12,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,...,10,0,both,Mid_range_price,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,...,9,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,28,Regular customer,6.607122
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,...,9,1,both,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,...,7,1,both,Mid_range_price,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,...,6,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,28,Regular customer,6.607122
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,...,6,1,both,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,...,10,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,28,Regular customer,6.607122
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,...,3,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,28,Regular customer,6.607122
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,...,5,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,...,11,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,...,11,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,...,5,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,...,15,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,...,4,1,both,Mid_range_price,Least busy,Least busy days,Average orders,28,Regular customer,6.607122
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,...,6,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,28,Regular customer,6.607122
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,...,1,1,both,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,...,1,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,...,2,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,4,New customer,7.123529
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,...,2,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,4,New customer,7.123529
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,...,3,1,both,Mid_range_price,Least busy,Least busy days,Average orders,4,New customer,7.123529
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,...,1,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,10,New customer,4.853521
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,...,6,1,both,Mid_range_price,Busiest day,Busiest days,Most orders,10,New customer,4.853521
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,...,3,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,10,New customer,4.853521

In [48]:
# create a flag column depeding on the mean price. use .loc 
# If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
# If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

df_orders_products_merge.loc[df_orders_products_merge['mean_price'] < 10, 'spending_flag'] = 'Low spender'
df_orders_products_merge.loc[df_orders_products_merge['mean_price'] >= 10, 'spending_flag'] = 'High spender'

In [53]:
# check functionality through value_counts()
df_orders_products_merge['spending_flag'].value_counts()

spending_flag
Low spender     31770614
High spender      634245
Name: count, dtype: int64

### 7. Creating a frequency flag column for customers

In [56]:
# create an aggregated column using tranform('median'). groupby()
df_orders_products_merge['median_prior_days'] = df_orders_products_merge.groupby(['user_id'])['days_since_prior_order'].transform('median')

In [59]:
# check functionality 
df_orders_products_merge.head(1)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,...,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_prior_days
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender,8.0

In [60]:
# create a flag column with the following conditions 
# If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer”
# If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer”
# If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer”

df_orders_products_merge.loc[df_orders_products_merge['median_prior_days'] > 20, 'frequency_flag'] = 'Non-frequent customer'
df_orders_products_merge.loc[(df_orders_products_merge['median_prior_days'] <= 20) & (df_orders_products_merge['median_prior_days'] > 10), 'frequency_flag'] = 'Regular customer'
df_orders_products_merge.loc[df_orders_products_merge['median_prior_days'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [64]:
# check functionality
df_orders_products_merge.head(50)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,...,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_prior_days,frequency_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid_range_price,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid_range_price,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid_range_price,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid_range_price,Regularly busy,Least busy days,Most orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid_range_price,Least busy,Least busy days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,Mid_range_price,Regularly busy,Busiest days,Average orders,26,Regular customer,6.935398,Low spender,11.0,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,Mid_range_price,Regularly busy,Regularly busy,Most orders,9,New customer,5.957576,Low spender,20.0,Regular customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,Mid_range_price,Regularly busy,Least busy days,Most orders,12,Regular customer,6.680000,Low spender,6.0,Frequent customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,Mid_range_price,Regularly busy,Busiest days,Average orders,20,Regular customer,7.162500,Low spender,10.0,Frequent customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,Mid_range_price,Regularly busy,Busiest days,Most orders,20,Regular customer,7.162500,Low spender,10.0,Frequent customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,...,Mid_range_price,Regularly busy,Regularly busy,Most orders,10,New customer,5.813636,Low spender,20.0,Regular customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,...,Mid_range_price,Regularly busy,Least busy days,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,...,Mid_range_price,Least busy,Least busy days,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,...,Mid_range_price,Regularly busy,Regularly busy,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,...,Mid_range_price,Regularly busy,Least busy days,Most orders,13,Regular customer,6.803797,Low spender,7.0,Frequent customer
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,...,Mid_range_price,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797,Low spender,7.0,Frequent customer
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,...,Mid_range_price,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797,Low spender,7.0,Frequent customer
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,...,Mid_range_price,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,...,Mid_range_price,Regularly busy,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,...,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,...,Mid_range_price,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,...,Mid_range_price,Regularly busy,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,...,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,...,Mid_range_price,Regularly busy,Busiest days,Most orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,...,Mid_range_price,Regularly busy,Busiest days,Most orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,...,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,...,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,...,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,...,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,...,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,...,Mid_range_price,Least busy,Least busy days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,...,Mid_range_price,Regularly busy,Regularly busy,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,...,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,...,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer,6.607122,Low spender,7.0,Frequent customer
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,...,Mid_range_price,Regularly busy,Regularly busy,Most orders,4,New customer,7.123529,Low spender,2.0,Frequent customer
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,...,Mid_range_price,Regularly busy,Regularly busy,Most orders,4,New customer,7.123529,Low spender,2.0,Frequent customer
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,...,Mid_range_price,Least busy,Least busy days,Average orders,4,New customer,7.123529,Low spender,2.0,Frequent customer
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,...,Mid_range_price,Regularly busy,Busiest days,Average orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,...,Mid_range_price,Busiest day,Busiest days,Most orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,...,Mid_range_price,Regularly busy,Busiest days,Average orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,...,Mid_range_price,Busiest day,Busiest days,Average orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,...,Mid_range_price,Least busy,Least busy days,Most orders,10,New customer,4.853521,Low spender,25.0,Non-frequent customer
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,...,Mid_range_price,Busiest day,Busiest days,Most orders,10,New customer,7.377143,Low spender,13.0,Regular customer
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,...,Mid_range_price,Regularly busy,Busiest days,Average orders,23,Regular customer,8.054153,Low spender,7.0,Frequent customer
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,...,Mid_range_price,Regularly busy,Busiest days,Average orders,25,Regular customer,8.353793,Low spender,11.0,Regular customer
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,...,Mid_range_price,Regularly busy,Least busy days,Most orders,13,Regular customer,6.452800,Low spender,7.0,Frequent customer
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,...,Mid_range_price,Regularly busy,Regularly busy,Average orders,5,New customer,7.960606,Low spender,28.0,Non-frequent customer
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,...,Mid_range_price,Regularly busy,Regularly busy,Most orders,6,New customer,6.322222,Low spender,18.0,Regular customer
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,...,Mid_range_price,Regularly busy,Busiest days,Most orders,3,New customer,7.511111,Low spender,21.0,Non-frequent customer
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,...,Mid_range_price,Regularly busy,Busiest days,Most orders,42,Loyal customer,7.441100,Low spender,7.0,Frequent customer

### 9. Exporting Data

In [66]:
df_orders_products_merge.to_pickle(os.path.join(data_path, 'Prepared Data', 'orders_products_merge_group.pkl'))

In [67]:
# check shape
df_orders_products_merge.shape

(32404859, 24)