### Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

### Importing Data

In [2]:
# establishes data path
data_path = r'C:\Users\gerar\CareerFoundry Python\Instacart Basket Analysis\02 Data'

In [3]:
# imports pickle file into a panda dataframe 
df_orders_products_merge = pd.read_pickle(os.path.join(data_path, 'Prepared Data', 'orders_products_merge_busy.pkl'))

In [4]:
# creates test dataframe
df_test = df_orders_products_merge[:1000000]

In [5]:
df_test.head(1)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders

In [6]:
# uses grouby function. This only groups data according to a specific column
df_test.groupby('department_id')

In [7]:
# use  groupby().agg() for a single aggregation (BEST PRACTICE)
df_test.groupby('department_id').agg({'customer_order_count': ['mean']})

              customer_order_count
                              mean
department_id
1                        15.577493
2                        17.320781
3                        16.084944
4                        17.530458
5                        14.763075
6                        16.658449
7                        17.031590
8                        15.076662
9                        15.447580
10                       18.681852
11                       15.447411
12                       14.327957
13                       16.548642
14                       16.960241
15                       16.121948
16                       17.803851
17                       15.593633
18                       19.674252
19                       16.899756
20                       16.255442
21                       25.535479

In [8]:
# alternative way to calculate mean (not best practice)
df_test.groupby('department_id')['customer_order_count'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: customer_order_count, dtype: float64

In [9]:
# calculating multiple aggregations
df_test.groupby('department_id').agg({'customer_order_count' : ['mean', 'min', 'max']})

              customer_order_count
                              mean min max
department_id
1                        15.577493   1  99
2                        17.320781   1  96
3                        16.084944   1  99
4                        17.530458   1  99
5                        14.763075   1  99
6                        16.658449   1  99
7                        17.031590   1  99
8                        15.076662   1  98
9                        15.447580   1  99
10                       18.681852   1  99
11                       15.447411   1  99
12                       14.327957   1  99
13                       16.548642   1  99
14                       16.960241   1  99
15                       16.121948   1  99
16                       17.803851   1  99
17                       15.593633   1  99
18                       19.674252   1  99
19                       16.899756   1  99
20                       16.255442   1  99
21                       25.535479   1  98

In [11]:
df_test.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid_range_price,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid_range_price,Least busy,Least busy days,Average orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders

In [12]:
# create a flag column using an aggregated criteria through transform()
df_test['max_order'] = df_test.groupby(['user_id'])['customer_order_count'].transform(np.max)

C:\Users\gerar\AppData\Local\Temp\ipykernel_16076\3422672329.py:2: FutureWarning: The provided callable <function max at 0x000001542C3A45E0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_test['max_order'] = df_test.groupby(['user_id'])['customer_order_count'].transform(np.max)
C:\Users\gerar\AppData\Local\Temp\ipykernel_16076\3422672329.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['max_order'] = df_test.groupby(['user_id'])['customer_order_count'].transform(np.max)

In [13]:
df_test.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,30
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,30
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid_range_price,Least busy,Least busy days,Average orders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,8
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,20
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,23
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,16
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,21

In [23]:
pd.options.display.max_rows = None

In [14]:
df_test.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,30
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,30
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid_range_price,Least busy,Least busy days,Average orders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,8
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,20
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,23
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,16
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,21

In [20]:
# declares empty list that will fill the 'busiest_period_of_day' column
list_flag_values = []

# for loop that fills the empty list 
for value in df_test['max_order']:  
    if value > 40:
        list_flag_values.append('Loyal customer')
    elif value <= 40 and value > 10:
        list_flag_values.append('Regular customer')
    else:
        list_flag_values.append('New customer')

In [21]:
df_test['loyalty_flag'] = list_flag_values

C:\Users\gerar\AppData\Local\Temp\ipykernel_16076\2973126647.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['loyalty_flag'] = list_flag_values

In [24]:
df_test.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,customer_order_count,order_day_of_the_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,30,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,30,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid_range_price,Least busy,Least busy days,Average orders,3,New customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,16,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,3,New customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,12,Regular customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,18,Regular customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,18,Regular customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,1,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,6,New customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,1,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,41,Loyal customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,3,1,both,Mid_range_price,Least busy,Least busy days,Most orders,41,Loyal customer
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,4,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,41,Loyal customer
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,8,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,9,New customer
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.0,18,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,9,New customer
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.0,12,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,9,New customer
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.0,10,0,both,Mid_range_price,Regularly busy,Regularly busy,Fewest orders,28,Regular customer
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.0,9,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,28,Regular customer
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.0,9,1,both,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,8.0,7,1,both,Mid_range_price,Regularly busy,Regularly busy,Fewest orders,28,Regular customer
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,6.0,6,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,28,Regular customer
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,28.0,6,1,both,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,7.0,10,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,28,Regular customer
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,7.0,3,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,28,Regular customer
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,0.0,5,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,7.0,11,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,7.0,11,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,7.0,5,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,7.0,15,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,3.0,4,1,both,Mid_range_price,Least busy,Least busy days,Average orders,28,Regular customer
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,16.0,6,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,28,Regular customer
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,5.0,1,1,both,Mid_range_price,Regularly busy,Busiest days,Fewest orders,28,Regular customer
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,6.0,1,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,28,Regular customer
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,NaN,2,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,3,New customer
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,21.0,2,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,3,New customer
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,2.0,3,1,both,Mid_range_price,Least busy,Least busy days,Average orders,3,New customer
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,NaN,1,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,9,New customer
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,18.0,6,1,both,Mid_range_price,Busiest day,Busiest days,Most orders,9,New customer
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,8.0,3,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,9,New customer
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,30.0,10,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,9,New customer
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,25.0,1,1,both,Mid_range_price,Least busy,Least busy days,Most orders,9,New customer
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,NaN,12,0,both,Mid_range_price,Busiest day,Busiest days,Most orders,1,New customer
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,9.0,10,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,21,Regular customer
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,10.0,5,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,24,Regular customer
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,7.0,11,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,10,New customer
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,NaN,8,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,4,New customer
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,30.0,7,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,4,New customer
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,NaN,2,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,1,New customer
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,7.0,8,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,40,Regular customer
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,10,7.0,2,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,40,Regular customer
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,13,7.0,6,1,both,Mid_range_price,Regularly busy,Least busy days,Most orders,40,Regular customer
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,11,5.0,3,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,40,Regular customer
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,11,4.0,2,1,both,Mid_range_price,Regularly busy,Busiest days,Most orders,40,Regular customer
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,7,8.0,1,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,40,Regular customer
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,8,30.0,2,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,2,New customer
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,16,NaN,9,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,4,New customer
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,16,29.0,1,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,3,New customer
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,13,12.0,7,0,both,Mid_range_price,Busiest day,Busiest days,Most orders,6,New customer
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,15,NaN,11,0,both,Mid_range_price,Least busy,Least busy days,Most orders,1,New customer
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,23,4.0,6,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,5,New customer
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,15,5.0,5,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,21,Regular customer
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,17,5.0,6,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,21,Regular customer
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,8,13.0,3,1,both,Mid_range_price,Regularly busy,Busiest days,Average orders,21,Regular customer
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,15,10.0,2,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,30,Regular customer
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,23,6.0,1,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,30,Regular customer
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,23,9.0,1,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,30,Regular customer
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,13,6.0,2,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,30,Regular customer
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,16,8.0,2,1,both,Mid_range_price,Regularly busy,Least busy days,Average orders,30,Regular customer
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,13,1.0,13,0,both,Mid_range_price,Least busy,Least busy days,Most orders,98,Loyal customer
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,7.0,2,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,35,Regular customer
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,21.0,2,0,both,Mid_range_price,Least busy,Least busy days,Most orders,8,New customer
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,30.0,2,0,both,Mid_range_price,Busiest day,Busiest days,Most orders,3,New customer
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,30.0,1,1,both,Mid_range_price,Regularly busy,Least busy days,Most orders,3,New customer
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,NaN,11,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,1,New customer
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,17,30.0,3,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,23,Regular customer
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,18,8.0,2,1,both,Mid_range_price,Least busy,Least busy days,Average orders,23,Regular customer
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,15,7.0,1,1,both,Mid_range_price,Least busy,Least busy days,Most orders,23,Regular customer
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,21,14.0,2,1,both,Mid_range_price,Least busy,Least busy days,Average orders,23,Regular customer
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,18,28.0,1,1,both,Mid_range_price,Least busy,Least busy days,Average orders,23,Regular customer
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,7,16.0,4,1,both,Mid_range_price,Least busy,Least busy days,Average orders,23,Regular customer
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,22,1.0,1,1,both,Mid_range_price,Least busy,Least busy days,Average orders,23,Regular customer
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,16,14.0,1,1,both,Mid_range_price,Least busy,Least busy days,Average orders,23,Regular customer
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,15,7.0,2,1,both,Mid_range_price,Least busy,Least busy days,Most orders,23,Regular customer
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,13,8.0,1,1,both,Mid_range_price,Least busy,Least busy days,Most orders,23,Regular customer
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,14,16.0,7,1,both,Mid_range_price,Least busy,Least busy days,Most orders,23,Regular customer
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,18,8.0,16,0,both,Mid_range_price,Least busy,Least busy days,Average orders,17,Regular customer
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,18,14.0,5,0,both,Mid_range_price,Least busy,Least busy days,Average orders,8,New customer
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,16,NaN,2,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,1,New customer
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,16,8.0,8,0,both,Mid_range_price,Regularly busy,Busiest days,Average orders,22,Regular customer
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,14,14.0,15,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,21,Regular customer
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,14,14.0,9,1,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,21,Regular customer
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,21,10.0,1,0,both,Mid_range_price,Busiest day,Busiest days,Average orders,36,Regular customer
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,19,14.0,4,1,both,Mid_range_price,Busiest day,Busiest days,Average orders,36,Regular customer
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,16,4.0,2,1,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,36,Regular customer
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,8,New customer
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid_range_price,Regularly busy,Busiest days,Most orders,20,Regular customer
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid_range_price,Regularly busy,Regularly busy,Average orders,23,Regular customer
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid_range_price,Regularly busy,Least busy days,Most orders,16,Regular customer
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid_range_price,Regularly busy,Regularly busy,Most orders,21,Regular customer

In [25]:
df_test['loyalty_flag'].value_counts()

loyalty_flag
Regular customer    473070
Loyal customer      287917
New customer        239013
Name: count, dtype: int64

In [28]:
df_test[['user_id', 'customer_order_count', 'loyalty_flag']].head(60)

    user_id  customer_order_count      loyalty_flag
0       138                    28  Regular customer
1       138                    30  Regular customer
2       709                     2      New customer
3       764                     1      New customer
4       764                     3      New customer
5       777                    16  Regular customer
6       825                     3      New customer
7       910                    12  Regular customer
8      1052                    10  Regular customer
9      1052                    15  Regular customer
10     1379                     1      New customer
11     1480                    36    Loyal customer
12     1480                    38    Loyal customer
13     1480                    39    Loyal customer
14     1494                     6      New customer
15     1494                     7      New customer
16     1494                     9      New customer
17     1540                     4  Regular customer
18     1540                     5  Regular customer
19     1540                     6  Regular customer
20     1540                     7  Regular customer
21     1540                     8  Regular customer
22     1540                     9  Regular customer
23     1540                    14  Regular customer
24     1540                    15  Regular customer
25     1540                    18  Regular customer
26     1540                    19  Regular customer
27     1540                    20  Regular customer
28     1540                    21  Regular customer
29     1540                    22  Regular customer
30     1540                    24  Regular customer
31     1540                    25  Regular customer
32     1540                    27  Regular customer
33     1540                    28  Regular customer
34     1598                     1      New customer
35     1598                     2      New customer
36     1598                     3      New customer
37     1647                     1      New customer
38     1647                     4      New customer
39     1647                     6      New customer
40     1647                     8      New customer
41     1647                     9      New customer
42     2833                     1      New customer
43     2850                     7  Regular customer
44     2857                    24  Regular customer
45     3010                     5      New customer
46     3029                     1      New customer
47     3395                     4      New customer
48     3904                     1      New customer
49     4006                     2  Regular customer
50     4006                     3  Regular customer
51     4006                     5  Regular customer
52     4006                     9  Regular customer
53     4006                    12  Regular customer
54     4122                    11  Regular customer
55     4141                     2      New customer
56     4343                     1      New customer
57     4553                     3      New customer
58     4845                     6      New customer
59     6866                     1      New customer